// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlashMessagesController from "./flash_messages_controller"
application.register("flash-messages", FlashMessagesController)

import ImaskController from "./imask_controller"
application.register("imask", ImaskController)

import InssController from "./inss_controller"
application.register("inss", InssController)

import PieChartController from "./pie_chart_controller"
application.register("pie-chart", PieChartController)

import RailsNestedForm from "@stimulus-components/rails-nested-form";
application.register("nested-form", RailsNestedForm);

import ZipController from "./zip_controller"
application.register("zip", ZipController)
